### ISSUE TITLE
优化站点

### ISSUE THREAD

**Issue by whinc** [whinc/whinc.github.io#31]
- [ ] 优化字体尺寸
- [ ] 优化博客：最大化利用屏幕，左侧文章列表，右侧文章目录，中间区域留给文章内容
- [ ] 支持文章评论，github 登录
- [ ] 源码中将 docs 和 assets 提取到根目录，方便编辑文章
- [ ] 申请独立域名

> 参考这个博客站点 https://zxuqian.cn/

**Comment by xiaomazi888** [comment]
您发的邮件我已经收到，我会认真查收，感谢您对我的工作的支持。

**Comment by xiaomazi888** [comment]
您发的邮件我已经收到，我会认真查收，感谢您对我的工作的支持。
